<?php declare(strict_types = 1);

namespace App\Service;

final class RulesetGeneratorService
{

	/**
	 * @param array<string> $sniffs
	 * @param array<string, array<string, mixed>> $properties
	 */
	public function generate(array $sniffs, array $properties = []): string
	{
		$xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
		$xml .= '<ruleset name="Custom Ruleset">' . "\n";
		$xml .= "\t" . '<description>Generated by Codestyler Playground</description>' . "\n\n";

		// Add encoding
		$xml .= "\t" . '<arg name="encoding" value="utf-8"/>' . "\n";
		$xml .= "\t" . '<arg value="p"/>' . "\n";
		$xml .= "\t" . '<arg value="s"/>' . "\n";
		$xml .= "\t" . '<arg name="colors"/>' . "\n\n";

		// Add file extensions
		$xml .= "\t" . '<arg name="extensions" value="php,phpt"/>' . "\n\n";

		foreach ($sniffs as $sniff) {
			$sniffProperties = $properties[$sniff] ?? [];

			if (empty($sniffProperties)) {
				$xml .= "\t" . '<rule ref="' . htmlspecialchars($sniff) . '"/>' . "\n";
			} else {
				$xml .= "\t" . '<rule ref="' . htmlspecialchars($sniff) . '">' . "\n";
				$xml .= "\t\t" . '<properties>' . "\n";

				foreach ($sniffProperties as $name => $value) {
					if (is_array($value)) {
						$xml .= "\t\t\t" . '<property name="' . htmlspecialchars($name) . '" type="array">' . "\n";
						foreach ($value as $key => $val) {
							$xml .= "\t\t\t\t" . '<element key="' . htmlspecialchars((string) $key) . '" value="' . htmlspecialchars((string) $val) . '"/>' . "\n";
						}

						$xml .= "\t\t\t" . '</property>' . "\n";
					} else {
						$xml .= "\t\t\t" . '<property name="' . htmlspecialchars($name) . '" value="' . htmlspecialchars((string) $value) . '"/>' . "\n";
					}
				}

				$xml .= "\t\t" . '</properties>' . "\n";
				$xml .= "\t" . '</rule>' . "\n";
			}
		}

		return $xml . '</ruleset>' . "\n";
	}

}
